default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 100
  workers:
    - queues: critical
      threads: 3
      processes: 1
      polling_interval: 0.2
    - queues: [events, default]
      threads: 2
      processes: 1
      polling_interval: 0.5
    - queues: files
      threads: 1
      processes: 1
      polling_interval: 0.5
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
