apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mesh-files
  namespace: mesh-showcase
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
