source "https://rubygems.org"

gem "rails", "8.1.4"
gem "pg"
gem "puma"
gem "bcrypt"
gem "pundit"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "rubyzip", "3.7.0", require: "zip"
gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-rails"
gem "opentelemetry-instrumentation-active_job"
gem "opentelemetry-instrumentation-pg"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "brakeman", require: false
  gem "bundler-audit", require: false
  gem "rubocop-rails-omakase", require: false
  gem "packwerk", require: false
  gem "steep", require: false
end
